### ISSUE TITLE
Passo a passo local

### ISSUE THREAD

**Issue by geich** [allan-nubling/Zaply-11-2020#2]
Olá Allan! 

Ótimo projeto, porém senti falta do passo a passo para **rodar ele localmente**. Como as configs do **banco** e um exemplo da `.env`, pode adicionar no `Readme.md`?

**Comment by geich** [comment]
Ops o git deu 404 aqui e duplicou as issues kk. pode responder nessa.

**Comment by allan-nubling** [comment]
Opa, coloquei lá no readme.md e estou enviando aqui uma cópia do arquivo .env também.
Obrigado!


[env-file.txt](https://github.com/allan-nubling/Zaply-11-2020/files/5538840/env-file.txt)
